kvAgregated_SOURCES += \
	src/aggregator/AbstractAggregator.h \
	src/aggregator/AbstractAggregator.cc \
	src/aggregator/StandardAggregator.h \
	src/aggregator/StandardAggregator.cc \
	src/aggregator/minmax.h \
	src/aggregator/minmax.cc \
	src/aggregator/ra2rr_12.h \
	src/aggregator/ra2rr_12.cc \
	src/aggregator/ra2rr_12_forward.h \
	src/aggregator/ra2rr_12_forward.cc \
	src/aggregator/rr.h \
	src/aggregator/rr.cc \
	src/aggregator/rr_1.h \
	src/aggregator/rr_1.cc \
	src/aggregator/rr_12.h \
	src/aggregator/rr_12.cc \
	src/aggregator/rr_24.h \
	src/aggregator/rr_24.cc \
	src/aggregator/MeanValueAggregator.h \
	src/aggregator/MeanValueAggregator.cc \
	src/aggregator/ta_24.h \
	src/aggregator/ta_24.cc \
	src/aggregator/KoppenBasedMeanValueAggregator.h \
	src/aggregator/KoppenBasedMeanValueAggregator.cc \
	src/aggregator/uu_24.h \
	src/aggregator/uu_24.cc \
	src/aggregator/nn_24.h \
	src/aggregator/nn_24.cc \
	src/aggregator/po.h \
	src/aggregator/po.cc
